### PR TITLE
Optimized Graph Edit for GPU Inference with *.pb Models

### PR DESCRIPTION
**Pull request by jiaxiang-wu**
**Abstract:**
Optimize the graph edit method for faster GPU inference with *.pb models.

**Description:**
In order to speed-up the inference time of channel pruned models, we need to rewrite the graph to take advantage of reduced computation due to all-zero channels. There are two possible ways to do so:
* **1x1 conv + standard conv**: use 1x1 conv to obtain feature maps with non-zero channels only, and then apply the standard convolutional operation. This will introduce extra computation due to 1x1 conv and slow the compressed model down. Particularly, this will not bring speed-up for pointwise convolution, which is widely used in MobileNet and ResNet's bottleneck structure.
* **gather + standard conv**: use tf.gather to filter out all-zero channels, and then apply the standard convolutional operation. However, tf.gather is not fully supported by TensorFlow Lite, and cannot be used for TF-Lite based deployment.

Previously, we only provide the first approach to export a channel pruned model to *.pb and *.tflite models. Although the speed-up for CPU-based inference with *.tflite models is observed, the GPU-based inference time with *.pb models is often longer, due to extra computation, as noticed in #83 and #95. In this pull request, we implement the second approach to optimize GPU-based inference.

Detailed documentation is coming soon.

**Note:**
1. The second approach runs faster with NCHW data format, which is not supported by TensorFlow Lite. Thus, we only provide the conversion code to *.pb models.
2. Before using the second approach, you need to convert the data format of channel pruned models from NHWC to NCHW, using `tools/conversion/convert_data_format.py`.
3. The speed-up on ILSVRC-12 in more significant than CIFAR-10. Maybe CIFAR-10 models are too small?
4. MobileNet does not support the NCHW data format, so we cannot test the second approach on it.

**Some Results:**
channel_pruned_models_speed

### CODE REVIEW

**Comment by dhingratul** [comment]
@jiaxiang-wu Is this for both --learner channel and --learner dis-chn-pruned

**Comment by jiaxiang-wu** [comment]
@dhingratul Yes, the model conversion script detects all-zero channels in the checkpoint files. It does not care which learner, `ChannelPrunedLearner` / `ChannelPrunedGpuLearner` / `DisChnPrunedLearner`, is used to generate this checkpoint file.

**Comment by dhingratul** [comment]
@jiaxiang-wu This speedup is not reproducible on 1080Ti; 17ms for original and 21ms for transformed

**Comment by to-be-snail** [comment]
I have read the codes in export_chn_pruned_tflite_model.py and have generated the original_model.pb and transformed_model.pb of MobileNet v1. I have found the difference between the two models is small,the original model is 12000+kb and the transformed model is 11000+kb,and both of their inference time is 5+ms.

**Pull request merged**
